language: python
dist: xenial

matrix:
  include:
    - python: 3.7
      env: TOXENV=py,flake8,sphinx-dev,codecov
    - python: 3.8
      env: TOXENV=py,flake8,sphinx-dev,codecov
    - python: 3.9
      env: TOXENV=py,flake8,sphinx-dev,codecov
    - python: 3.10
      env: TOXENV=py,flake8,sphinx-dev,codecov
    - python: pypy
      env: TOXENV=py,flake8,sphinx-dev,codecov
    - python: pypy3
      env: TOXENV=py,flake8,sphinx-dev,codecov

install:
  - pip install tox

script:
  - tox
